<?php

return [
    'Default' => [
        'captcha_type'        => 'string',
        'code_length'         => 6,
        'charset'             => 'abcdefghijkmnopqrstuvwxzyABCDEFGHJKLMNPQRSTUVWXZY23456789',
        'case_sensitive'      => false,
        'use_wordlist'        => false,
        'wordlist_file'       => WWW_ROOT . 'files' . DIRECTORY_SEPARATOR . 'words.txt',
        'image_width'         => 215,
        'image_height'        => 80,
        'font_ratio'          => 0.4,
        'ttf_files'           => [
            WWW_ROOT . 'fonts' . DIRECTORY_SEPARATOR . 'BDLatn1.ttf',
            WWW_ROOT . 'fonts' . DIRECTORY_SEPARATOR . 'BDLatn2.ttf',
            WWW_ROOT . 'fonts' . DIRECTORY_SEPARATOR . 'BDLatn3.ttf',
            WWW_ROOT . 'fonts' . DIRECTORY_SEPARATOR . 'AHGBold.ttf',
        ],
        'image_bg_color'      => '#ffffff',
        'text_color'          => '#707070',
        'line_color'          => '#707070',
        'noise_color'         => '#707070',
        'num_lines'           => 5,
        'noise_level'         => 2,
        'perturbation'        => 0.85,
        'use_random_spaces'   => false,
        'use_text_angles'     => false,
        'use_random_baseline' => false,
        'use_random_boxes'    => false,
        'background_directory' => null,
        'image_signature'     => '',
        'signature_color'     => '#707070',
        'timeout'             => 900,
    ],
    'Login' => [
        'captcha_type'        => 'string',
        'code_length'         => 4,
        'charset'             => 'abcdefghijkmnopqrstuvwxzyABCDEFGHJKLMNPQRSTUVWXZY23456789',
        'case_sensitive'      => false,
        'use_wordlist'        => false,
        'wordlist_file'       => WWW_ROOT . 'files' . DIRECTORY_SEPARATOR . 'words.txt',
        'image_width'         => 180,
        'image_height'        => 50,
        'font_ratio'          => 0.4,
        'ttf_files'           => [
            WWW_ROOT . 'fonts' . DIRECTORY_SEPARATOR . 'BDLatn1.ttf',
            WWW_ROOT . 'fonts' . DIRECTORY_SEPARATOR . 'BDLatn2.ttf',
            WWW_ROOT . 'fonts' . DIRECTORY_SEPARATOR . 'BDLatn3.ttf',
            WWW_ROOT . 'fonts' . DIRECTORY_SEPARATOR . 'AHGBold.ttf',
        ],
        'image_bg_color'      => '#ffffff',
        'text_color'          => '#707070',
        'line_color'          => '#707070',
        'noise_color'         => '#707070',
        'num_lines'           => 3,
        'noise_level'         => 1,
        'perturbation'        => 0.75,
        'use_random_spaces'   => false,
        'use_text_angles'     => false,
        'use_random_baseline' => false,
        'use_random_boxes'    => false,
        'background_directory' => null,
        'image_signature'     => '',
        'signature_color'     => '#707070',
        'timeout'             => 300,
    ],
];
